# GRPC config
GRPC_MAX_WORKER = 10
GRPC_PORT = 50051

# CPLEX
CPLEX_GAP = 0.1
CPLEX_OPTIMALITY_TARGET = 0
CPLEX_DELTA = 0.9
CPLEX_FEASIBILITY = 10**-4
CPLEX_ENABLE_LOG = False # ENABLE LOG THƯ VIỆN CPLEX
CPLEX_EXPORT_MODEL = False # LOG MODEL