# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generated_protobuf.acm_cplex_solver_pb2 as acm__cplex__solver__pb2


class AcmCplexSolverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Solve = channel.unary_unary(
                '/AcmCplexSolver.AcmCplexSolver/Solve',
                request_serializer=acm__cplex__solver__pb2.ACSSolveRequest.SerializeToString,
                response_deserializer=acm__cplex__solver__pb2.ACSResultList.FromString,
                )


class AcmCplexSolverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Solve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcmCplexSolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Solve': grpc.unary_unary_rpc_method_handler(
                    servicer.Solve,
                    request_deserializer=acm__cplex__solver__pb2.ACSSolveRequest.FromString,
                    response_serializer=acm__cplex__solver__pb2.ACSResultList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AcmCplexSolver.AcmCplexSolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AcmCplexSolver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Solve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AcmCplexSolver.AcmCplexSolver/Solve',
            acm__cplex__solver__pb2.ACSSolveRequest.SerializeToString,
            acm__cplex__solver__pb2.ACSResultList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
